In [3]:
# Choosen example of webscrapping as database and API needs personal token or password to run
# Web scraping to import some data from website.

# Importing required packages for web scrapping
from bs4 import BeautifulSoup
import requests 
import pandas as pd

# Wikipedia URL
web_url = 'https://en.wikipedia.org/wiki/All-time_Commonwealth_Games_medal_table'

# get HTML we page
html_page = requests.get(web_url)

# display scrapped data
# print(soup.prettify())

web_status = html_page.status_code

if web_status == 200:
    # scrape webpage using beautifulsoup
    soup = BeautifulSoup(html_page.content, "html.parser")
    # Find medal table in html
    medal_table = soup.find('table',{'class':'wikitable sortable plainrowheaders jquery-tablesorter'})
    df=pd.read_html(str(medal_table))
    # convert list to pandas dataframe
    countries_medal_table=pd.DataFrame(df[0])
    print(countries_medal_table)
else:
    print("Website URL is not accessible")
    print(f"Web URL status response : {web_status}")

                   Rank                    CGA  Gold  Silver  Bronze  Total
0                     1        Australia (AUS)  1001     832     763   2596
1                     2          England (ENG)   773     783     766   2322
2                     3           Canada (CAN)   510     548     589   1647
3                     4            India (IND)   203     190     171    564
4                     5      New Zealand (NZL)   179     232     295    706
..                  ...                    ...   ...     ...     ...    ...
60                   61   Norfolk Island (NFI)     0       0       2      2
61                   62     Cook Islands (COK)     0       0       1      1
62                   62             Niue (NIU)     0       0       1      1
63                   62  Solomon Islands (SOL)     0       0       1      1
64  Totals (64 entries)    Totals (64 entries)  3607    3601    3921  11129

[65 rows x 6 columns]

In [4]:
# Regex example

# Importing required libraries
import re

pattern = r"\w+\.txt(?=\serror)"

test_log_string = "Info.txt transferred, details.txt transferred, project.txt error,report.txt error"

print("List all failed transferred files")
re.findall(pattern, test_log_string)

List all failed transferred files

['project.txt', 'report.txt']

In [5]:
6+9

15

Requirement already satisfied: pandas in c:\users\fidelity\anaconda3\lib\site-packages (1.3.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\fidelity\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: numpy>=1.17.3 in c:\users\fidelity\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\fidelity\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in c:\users\fidelity\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)

In [7]:
import pandas

In [10]:
data=pandas.read_csv("adult.csv")

In [11]:
print(data)

       39          State-gov   77516    Bachelors   13        Never-married  \
0      50   Self-emp-not-inc   83311    Bachelors   13   Married-civ-spouse
1      38            Private  215646      HS-grad    9             Divorced
2      53            Private  234721         11th    7   Married-civ-spouse
3      28            Private  338409    Bachelors   13   Married-civ-spouse
4      37            Private  284582      Masters   14   Married-civ-spouse
...    ..                ...     ...          ...  ...                  ...
32555  27            Private  257302   Assoc-acdm   12   Married-civ-spouse
32556  40            Private  154374      HS-grad    9   Married-civ-spouse
32557  58            Private  151910      HS-grad    9              Widowed
32558  22            Private  201490      HS-grad    9        Never-married
32559  52       Self-emp-inc  287927      HS-grad    9   Married-civ-spouse

             Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0         Exec-managerial         Husband   White     Male      0   0   13
1       Handlers-cleaners   Not-in-family   White     Male      0   0   40
2       Handlers-cleaners         Husband   Black     Male      0   0   40
3          Prof-specialty            Wife   Black   Female      0   0   40
4         Exec-managerial            Wife   White   Female      0   0   40
...                   ...             ...     ...      ...    ...  ..  ...
32555        Tech-support            Wife   White   Female      0   0   38
32556   Machine-op-inspct         Husband   White     Male      0   0   40
32557        Adm-clerical       Unmarried   White   Female      0   0   40
32558        Adm-clerical       Own-child   White     Male      0   0   20
32559     Exec-managerial            Wife   White   Female  15024   0   40

        United-States   <=50K
0       United-States   <=50K
1       United-States   <=50K
2       United-States   <=50K
3                Cuba   <=50K
4       United-States   <=50K
...               ...     ...
32555   United-States   <=50K
32556   United-States    >50K
32557   United-States   <=50K
32558   United-States   <=50K
32559   United-States    >50K

[32560 rows x 15 columns]

In [12]:
data=pandas.read_csv("vh_data15.csv")
data

,County_Density,Vaccine_Trust_Index,Personal_Responsibility,Trust_Science_Apolitical,Trust_Science_Politicians,Trust_Science_Media,Trust_Science_Community,Trust_National,Trust_State,Trust_Local,...,Pandemic_Impact_Network,Infected_Personal,Infected_Network,Biden,Trump,Party_ID,Household_Income,Vaccine_Required,Evangelical,Vaccine_Hesitant
0,137.851795,0.000000,10.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,...,0.0,0.0,0.0,No,Yes,Republican,1.0,0,1.0,1
1,38.751406,9.000000,5.0,8.0,4.0,6.0,9.0,8.0,2.0,7.0,...,5.0,0.0,0.0,Yes,No,Democrat,3.0,0,0.0,0
2,18.103752,8.666667,7.0,6.0,1.0,1.0,6.0,7.0,7.0,9.0,...,6.0,0.0,1.0,No,Yes,Republican,6.0,0,0.0,0
3,26.912917,4.000000,7.0,6.0,6.0,4.0,6.0,6.0,6.0,6.0,...,7.0,0.0,0.0,Yes,No,Democrat,4.0,0,1.0,1
4,1541.026670,7.000000,6.0,6.0,1.0,2.0,6.0,6.0,2.0,7.0,...,2.5,0.0,1.0,Yes,Yes,Republican,3.0,0,1.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3348,470.033815,1.666667,8.0,0.0,0.0,0.0,0.0,2.0,2.0,4.0,...,7.5,0.0,0.0,No,Yes,Independent,8.0,0,1.0,1
3349,225.323560,9.333333,2.0,9.0,1.0,8.0,9.0,6.0,7.0,7.0,...,3.5,0.0,1.0,Yes,No,Republican,2.0,0,0.0,0
3350,108.474026,9.000000,8.0,6.0,3.0,3.0,5.0,6.0,7.0,6.0,...,6.0,0.0,0.0,No,Yes,Republican,2.0,1,0.0,0
3351,63.385677,9.333333,5.0,5.0,4.0,6.0,9.0,8.0,8.0,7.0,...,3.5,0.0,1.0,Yes,No,Democrat,12.0,1,0.0,0
3352,599.558111,9.000000,10.0,1.0,0.0,0.0,10.0,9.0,9.0,10.0,...,9.0,1.0,1.0,No,Yes,Republican,5.0,0,1.0,1

In [13]:
mean = data.mean()

C:\Users\Fidelity\AppData\Local\Temp/ipykernel_14296/315700382.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  mean = data.mean()

In [14]:
data["County_Density"].mean()

885.2094478130928

In [15]:
data.describe()

,County_Density,Vaccine_Trust_Index,Personal_Responsibility,Trust_Science_Apolitical,Trust_Science_Politicians,Trust_Science_Media,Trust_Science_Community,Trust_National,Trust_State,Trust_Local,...,Natural_Science_Literacy,College_Degree,Pandemic_Impact,Pandemic_Impact_Network,Infected_Personal,Infected_Network,Household_Income,Vaccine_Required,Evangelical,Vaccine_Hesitant
count,3336.000000,3353.000000,3347.000000,3344.000000,3345.000000,3346.000000,3346.000000,3349.000000,3349.000000,3351.000000,...,3352.000000,3352.000000,3348.000000,3347.000000,3311.000000,3352.000000,3348.000000,3353.000000,3352.000000,3353.000000
mean,885.209448,7.583408,7.033164,5.460227,2.326756,3.594740,6.494620,5.091072,5.540460,6.025664,...,0.763325,0.591289,4.772103,4.795937,0.050740,0.401253,6.348566,0.211452,0.179296,0.245154
std,2644.448478,2.532152,2.478438,2.851007,2.226946,2.952158,2.541518,2.431574,2.539518,2.251619,...,0.232633,0.491669,1.698135,1.685894,0.219499,0.490225,3.683644,0.408399,0.383657,0.430242
min,0.928098,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,108.451575,6.333333,5.000000,3.000000,0.000000,1.000000,5.000000,4.000000,4.000000,5.000000,...,0.666667,0.000000,4.000000,4.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000
50%,299.765383,8.333333,7.000000,5.000000,2.000000,4.000000,7.000000,5.000000,6.000000,6.000000,...,0.833333,1.000000,5.000000,5.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000
75%,717.797722,9.333333,9.000000,8.000000,4.000000,5.000000,8.000000,7.000000,8.000000,8.000000,...,1.000000,1.000000,5.500000,5.500000,0.000000,1.000000,10.000000,0.000000,0.000000,0.000000
max,27819.804800,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,...,1.000000,1.000000,10.000000,10.000000,1.000000,1.000000,12.000000,1.000000,1.000000,1.000000

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3353 entries, 0 to 3352
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   County_Density             3336 non-null   float64
 1   Vaccine_Trust_Index        3353 non-null   float64
 2   Personal_Responsibility    3347 non-null   float64
 3   Trust_Science_Apolitical   3344 non-null   float64
 4   Trust_Science_Politicians  3345 non-null   float64
 5   Trust_Science_Media        3346 non-null   float64
 6   Trust_Science_Community    3346 non-null   float64
 7   Trust_National             3349 non-null   float64
 8   Trust_State                3349 non-null   float64
 9   Trust_Local                3351 non-null   float64
 10  Trust_Media                3352 non-null   float64
 11  Perceived_Risk             3349 non-null   float64
 12  Perceived_Network_Risk     3348 non-null   float64
 13  Doctor_Comfort             3348 non-null   float64
 14  Fear_Needles               3349 non-null   float64
 15  Condition_Pregnancy        3252 non-null   float64
 16  Condition_Asthma           3252 non-null   float64
 17  Condition_Lung             3252 non-null   float64
 18  Condition_Diabetes         3252 non-null   float64
 19  Condition_Immune           3252 non-null   float64
 20  Condition_Obesity          3252 non-null   float64
 21  Condition_Heart            3252 non-null   float64
 22  Condition_Organ            3252 non-null   float64
 23  County_Cases               3336 non-null   float64
 24  County_Cases2wk            3336 non-null   float64
 25  Male                       3353 non-null   int64
 26  Race                       3353 non-null   int64
 27  Age                        3351 non-null   float64
 28  PS_Index                   3353 non-null   float64
 29  Natural_Science_Literacy   3352 non-null   float64
 30  College_Degree             3352 non-null   float64
 31  Pandemic_Impact            3348 non-null   float64
 32  Pandemic_Impact_Network    3347 non-null   float64
 33  Infected_Personal          3311 non-null   float64
 34  Infected_Network           3352 non-null   float64
 35  Biden                      3349 non-null   object
 36  Trump                      3348 non-null   object
 37  Party_ID                   3352 non-null   object
 38  Household_Income           3348 non-null   float64
 39  Vaccine_Required           3353 non-null   int64
 40  Evangelical                3352 non-null   float64
 41  Vaccine_Hesitant           3353 non-null   int64
dtypes: float64(35), int64(4), object(3)
memory usage: 1.1+ MB

In [ ]:
Test

In [19]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3353 entries, 0 to 3352
Data columns (total 42 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   County_Density             3336 non-null   float64
 1   Vaccine_Trust_Index        3353 non-null   float64
 2   Personal_Responsibility    3347 non-null   float64
 3   Trust_Science_Apolitical   3344 non-null   float64
 4   Trust_Science_Politicians  3345 non-null   float64
 5   Trust_Science_Media        3346 non-null   float64
 6   Trust_Science_Community    3346 non-null   float64
 7   Trust_National             3349 non-null   float64
 8   Trust_State                3349 non-null   float64
 9   Trust_Local                3351 non-null   float64
 10  Trust_Media                3352 non-null   float64
 11  Perceived_Risk             3349 non-null   float64
 12  Perceived_Network_Risk     3348 non-null   float64
 13  Doctor_Comfort             3348 non-null   float64
 14  Fear_Needles               3349 non-null   float64
 15  Condition_Pregnancy        3252 non-null   float64
 16  Condition_Asthma           3252 non-null   float64
 17  Condition_Lung             3252 non-null   float64
 18  Condition_Diabetes         3252 non-null   float64
 19  Condition_Immune           3252 non-null   float64
 20  Condition_Obesity          3252 non-null   float64
 21  Condition_Heart            3252 non-null   float64
 22  Condition_Organ            3252 non-null   float64
 23  County_Cases               3336 non-null   float64
 24  County_Cases2wk            3336 non-null   float64
 25  Male                       3353 non-null   int64
 26  Race                       3353 non-null   int64
 27  Age                        3351 non-null   float64
 28  PS_Index                   3353 non-null   float64
 29  Natural_Science_Literacy   3352 non-null   float64
 30  College_Degree             3352 non-null   float64
 31  Pandemic_Impact            3348 non-null   float64
 32  Pandemic_Impact_Network    3347 non-null   float64
 33  Infected_Personal          3311 non-null   float64
 34  Infected_Network           3352 non-null   float64
 35  Biden                      3349 non-null   object
 36  Trump                      3348 non-null   object
 37  Party_ID                   3352 non-null   object
 38  Household_Income           3348 non-null   float64
 39  Vaccine_Required           3353 non-null   int64
 40  Evangelical                3352 non-null   float64
 41  Vaccine_Hesitant           3353 non-null   int64
dtypes: float64(35), int64(4), object(3)
memory usage: 1.1+ MB

In [20]:
type(data)

pandas.core.frame.DataFrame

In [21]:
import pandas as pd

In [ ]:
data=pd.read_csv("vh_data15.csv")
data